version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis_nodequeue
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - ${REDIS_PORT}:6379
